### ISSUE TITLE
broken tests

### ISSUE THREAD

**Issue by siy** [bpatters/schemagen-graphql#1]
com.bretpatterson.schemagen.graphql.relay.RelayTest > testFindGames FAILED
    java.lang.AssertionError at RelayTest.java:144

com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapper_CollectionsTest > testGenericArrayListMapping FAILED
    java.lang.AssertionError at GraphQLObjectMapper_CollectionsTest.java:79

com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapper_CollectionsTest > testGenericCollectionsMapping FAILED
    java.lang.AssertionError at GraphQLObjectMapper_CollectionsTest.java:79

com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapper_CollectionsTest > testGenericListMappings FAILED
    java.lang.AssertionError at GraphQLObjectMapper_CollectionsTest.java:79

com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapper_CollectionsTest > testGenericHashSetMapping FAILED
    java.lang.AssertionError at GraphQLObjectMapper_CollectionsTest.java:79

com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapper_CollectionsTest > testGenericMapTypeMapping FAILED
    java.lang.ClassCastException at GraphQLObjectMapper_CollectionsTest.java:99

com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapper_CollectionsTest > testGenericTreeSetMapping FAILED
    java.lang.AssertionError at GraphQLObjectMapper_CollectionsTest.java:79

com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapper_CollectionsTest > testGenericLinkedListMapping FAILED
    java.lang.AssertionError at GraphQLObjectMapper_CollectionsTest.java:79

com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapper_CollectionsTest > testGenericSetMappings FAILED
    java.lang.AssertionError at GraphQLObjectMapper_CollectionsTest.java:79

com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapper_CollectionsTest > testGenericVectorMapping FAILED
    java.lang.AssertionError at GraphQLObjectMapper_CollectionsTest.java:79

com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapper_CollectionsTest > testRecursiveTypes FAILED
    java.lang.ClassCastException at GraphQLObjectMapper_CollectionsTest.java:354

com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapperTest > testEnumType FAILED
    java.lang.AssertionError at GraphQLObjectMapperTest.java:418

com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapperTest > testRelayConnectionType FAILED
    java.lang.AssertionError at GraphQLObjectMapperTest.java:125

com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapperTest > TestGenericObject FAILED
    java.lang.AssertionError at GraphQLObjectMapperTest.java:193

com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapperTest > testMethodBasedFields FAILED
    java.lang.AssertionError at GraphQLObjectMapperTest.java:365

com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapperTest > testMethodOnlyFields FAILED
    java.lang.AssertionError at GraphQLObjectMapperTest.java:402

**Comment by bpatters** [comment]
not sure what branch this is on, but master doesn't display this.

**Comment by siy** [comment]
Cloned repo from scratch and tried to run gradlew:

siy@siynb:~/Dropbox/My Exchange/ws/schemagen-graphql$ ./gradlew
:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
:processResources UP-TO-DATE
:classes
:jar
:schemagen-graphql-examples:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning
:schemagen-graphql-guava:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning
:schemagen-graphql-joda:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning
:schemagen-graphql-spring:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning
:compileTestJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning
:processTestResources UP-TO-DATE
:testClasses
:test

com.bretpatterson.schemagen.graphql.relay.RelayTest > testFindGames FAILED
    java.lang.AssertionError at RelayTest.java:144

com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapper_CollectionsTest > testGenericArrayListMapping FAILED
    java.lang.AssertionError at GraphQLObjectMapper_CollectionsTest.java:80

com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapper_CollectionsTest > testGenericCollectionsMapping FAILED
    java.lang.AssertionError at GraphQLObjectMapper_CollectionsTest.java:80

com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapper_CollectionsTest > testGenericListMappings FAILED
    java.lang.AssertionError at GraphQLObjectMapper_CollectionsTest.java:80

com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapper_CollectionsTest > testGenericHashSetMapping FAILED
    java.lang.AssertionError at GraphQLObjectMapper_CollectionsTest.java:80

com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapper_CollectionsTest > testGenericMapTypeMapping FAILED
    java.lang.ClassCastException at GraphQLObjectMapper_CollectionsTest.java:100

com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapper_CollectionsTest > testGenericTreeSetMapping FAILED
    java.lang.AssertionError at GraphQLObjectMapper_CollectionsTest.java:80

com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapper_CollectionsTest > testGenericLinkedListMapping FAILED
    java.lang.AssertionError at GraphQLObjectMapper_CollectionsTest.java:80

com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapper_CollectionsTest > testGenericSetMappings FAILED
    java.lang.AssertionError at GraphQLObjectMapper_CollectionsTest.java:80

com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapper_CollectionsTest > testGenericVectorMapping FAILED
    java.lang.AssertionError at GraphQLObjectMapper_CollectionsTest.java:80

com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapper_CollectionsTest > testRecursiveTypes FAILED
    java.lang.ClassCastException at GraphQLObjectMapper_CollectionsTest.java:355

com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapperTest > testEnumType FAILED
    java.lang.AssertionError at GraphQLObjectMapperTest.java:426

com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapperTest > testRelayConnectionType FAILED
    java.lang.AssertionError at GraphQLObjectMapperTest.java:134

com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapperTest > TestGenericObject FAILED
    java.lang.AssertionError at GraphQLObjectMapperTest.java:202

com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapperTest > testMethodBasedFields FAILED
    java.lang.AssertionError at GraphQLObjectMapperTest.java:373

com.bretpatterson.schemagen.graphql.impl.GraphQLObjectMapperTest > testMethodOnlyFields FAILED
    java.lang.AssertionError at GraphQLObjectMapperTest.java:410

35 tests completed, 16 failed
:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///home/siy/Dropbox/My%20Exchange/ws/schemagen-graphql/build/reports/tests/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 26.544 secs
