### ISSUE TITLE
AnnotationUtils breaks in Spring boot executable jar

### ISSUE THREAD

**Issue by cliedeman** [bpatters/schemagen-graphql#6]
Hello

I just tracked down a packaging bug caused by spring boot.
The default executable jar [format](http://docs.spring.io/spring-boot/docs/current/reference/html/executable-jar.html#executable-jar-system-classloader) messes with library package names and causes none of the default type mappers to be detected.

Would you accept a PR to Implement the change suggest by spring?

Ciaran

**Comment by bpatters** [comment]
sure I'm open to PR's from anyone who wants to make this project better.

**Comment by cliedeman** [comment]
Create PR #8
